name: Lint & Typecheck

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: npm
        cache-dependency-path: package-lock.json

    - name: Run lint and typecheck for base Code Bandit
      run: npm ci && npm run lint && npm run typecheck

    - name: Run lint and typecheck for Code Bandit VS Code Extension
      working-directory: vscode-extension
      run: npm ci && npm run lint && npm run typecheck